src/Entity/Recette.php
<?php
namespace App\Entity;
use DateTimeImmutable; 
use App\Repository\RecetteRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
 
#[UniqueEntity('name')]
#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: RecetteRepository::class)]
class Recette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\Length(min : 2, max :50)]
    #[Assert\NotBlank()]
    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[Assert\LessThan(1440)]
    #[Assert\Positive()]
    #[ORM\Column(nullable: true)]
    private ?int $time = null;

    #[ORM\Column(nullable: true)]
    #[Assert\LessThan(51)]
    #[Assert\Positive()] 
    private ?int $Nbpersonne = null;

    #[ORM\Column(nullable: true)]
    #[Assert\LessThan(6)]
    #[Assert\Positive()] 
    private ?int $difficulty = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $description = null;
   
    #[ORM\Column(nullable: true)]
    #[Assert\LessThan(1001)]
    #[Assert\Positive()]
    private ?float $prix = null;

    #[ORM\Column]
    private ?bool $IsFavorite = null;

    #[ORM\Column]
    #[Assert\NotNull]
    #[Assert\DateTime]
    private ?\DateTimeImmutable $CreatedAt = null;

    #[ORM\Column]
    #[Assert\NotNull]
    #[Assert\DateTime]
    private ?\DateTimeImmutable $UpdatedAt = null;


    #[ORM\ManyToMany(targetEntity: Ingredient::class)]
    
    private Collection $IngredientsL;
    public function __construct()
    {
        $this->IngredientsL = new ArrayCollection();
        $this->CreatedAt = new DateTimeImmutable;
        $this->UpdatedAt = new DateTimeImmutable;

    }
    #[ORM\PrePersist]
    public function setCreatedAtValue()
    {
       $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getTime(): ?int
    {
        return $this->time;
    }

    public function setTime(?int $time): static
    {
        $this->time = $time;

        return $this;
    }

    public function getNbpersonne(): ?int
    {
        return $this->Nbpersonne;
    }

    public function setNbpersonne(?int $Nbpersonne): static
    {
        $this->Nbpersonne = $Nbpersonne;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->difficulty;
    }

    public function setDifficulty(?int $difficulty): static
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }
    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }
  

    public function isIsFavorite(): ?bool
    {
        return $this->IsFavorite;
    }

    public function setIsFavorite(bool $IsFavorite): static
    {
        $this->IsFavorite = $IsFavorite;

        return $this;
    }
 
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeImmutable $CreatedAt): static
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }
 
    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->UpdatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $UpdatedAt): static
    {
        $this->UpdatedAt = $UpdatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredientsL(): Collection
    {
        return $this->IngredientsL;
    }
    public function __toString(): string
    {
        return $this->addIngredientsL;
    }

    public function addIngredientsL(Ingredient $ingredientsL): static
    {
        if (!$this->IngredientsL->contains($ingredientsL)) {
            $this->IngredientsL->add($ingredientsL);
        }

        return $this;
    }

    public function removeIngredientsL(Ingredient $ingredientsL): static
    {
        $this->IngredientsL->removeElement($ingredientsL);

        return $this;
    }
 
}

src/Form/RecetteType.php
<?php

namespace App\Form;
use App\Entity\Recette;
use App\Entity\Ingredient; // Assurez-vous d'inclure la classe Ingredient
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class RecetteType extends AbstractType
{
    public function buildForm(\Symfony\Component\Form\FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => 2,
                    'maxlength' => 50,
                ],
                'label' => 'Nom',
                'label_attr' => [
                    'class' => 'form-label mt-4',
                ],
                'constraints' => [
                    new Assert\Length(['min' => 2, 'max' => 50]),
                    new Assert\NotBlank(),
                ],
            ])
            ->add('prix', MoneyType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'label' => 'Prix',
                'label_attr' => [
                    'class' => 'form-label mt-4',
                ],
                'constraints' => [
                    new Assert\Positive(),
                    new Assert\LessThan(1001),
                ],
            ])
            ->add('time', IntegerType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => 1,
                    'maxlength' => 1440,
                ],
                'label' => 'Temps',
                'label_attr' => [
                    'class' => 'form-label mt-4',
                ],
                'constraints' => [
                    new Assert\NotBlank(),
                    new Assert\LessThan(1440),
                ],
            ])
            ->add('Nbpersonne', IntegerType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => 1,
                    'maxlength' => 50,
                ],
                'label' => 'Nombre de personnes',
                'label_attr' => [
                    'class' => 'form-label mt-4',
                ],
                'constraints' => [
                    new Assert\Positive(),
                    new Assert\LessThan(51),
                ],
            ])
            ->add('difficulty', RangeType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'min' => 1,
                    'max' => 5,
                ],
                'label' => 'Difficulté',
                'label_attr' => [
                    'class' => 'form-label mt-4',
                ],
                'constraints' => [
                    new Assert\Positive(),
                    new Assert\LessThan(6),
                ],
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'label' => 'Description',
                'label_attr' => [
                    'class' => 'form-label mt-4',
                ],
                'constraints' => [
                    new Assert\NotBlank(),
                ],
            ])
            ->add('IsFavorite', CheckboxType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'label' => 'Favori ?',
                'label_attr' => [
                    'class' => 'form-label mt-4',
                ],
                'constraints' => [
                    new Assert\NotNull(),
                ],
            ])
            ->add('ingredientsL', CollectionType::class, [
                'entry_type' => EntityType::class,
                'entry_options' => [
                    'class' => Ingredient::class,
                    'choice_label' => 'name',
                ],
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
            ])
            ->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recette::class,
        ]);
    }
}

src/Controller/RecetteController.php
<?php
namespace App\Controller;
use App\Repository\RecetteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Knp\Component\Pager\Pagination\SlidingPaginationInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use App\Entity\Recette;
use App\Form\RecetteType;

class RecetteController extends AbstractController
{
    #[Route('/recette', name: 'app_recette', methods: ['GET'])]
    public function index(RecetteRepository $repository, Request $request, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $repository->findAll(),
            $request->query->getInt('page', 1) 
        );

        $totalItemCount = ($pagination instanceof SlidingPaginationInterface) ? $pagination->getTotalItemCount() : 0;
       
        return $this->render('pages/recette/index.html.twig', [
            'recettes' => $pagination,
            'totalItemCount' => $totalItemCount,
        ]);
    }

    #[Route('/recette/new', name: 'recette.new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
    $recette = new Recette();
        $form = $this->createForm(RecetteType::class, $recette);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $ingredientExisting = $manager->getRepository(Recette::class)->findOneBy(['name' => $recette->getName()]);
            if ($recetteExisting) {
                // Handle the case where the ingredient with the same name already exists
                $this->addFlash('danger', 'Recette with this name already exists');
            } else {
                // The ingredient with the same name doesn't exist, proceed to persist and flush
                $this->addFlash('success', 'Votre recette a été créé avec succès');
                $manager->persist($recette);
                $manager->flush();
                
                // Redirect to the index page
                return $this->redirectToRoute('app_recette');
            }
        }

        return $this->render('pages/recette/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    
    #[Route('/recette/edit/{id}', name: 'recette.edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, EntityManagerInterface $manager, Recette $recette): Response
    {
        $form = $this->createForm(RecetteType::class, $recette);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $recette = $form->getData();
            $manager->persist($recette);
            $manager->flush();
            $this->addFlash(
                'success', 
                'Votre recette a été modifié avec succès');
                return $this->redirectToRoute('app_recette');
        }
            return $this->render('pages/recette/edit.html.twig', [
                'form' => $form->createView(),
            ]);
        }


        #[Route('/recette/delete/{id}', name: 'recette.delete', methods: ['GET'])]
        public function delete(Request $request, EntityManagerInterface $manager, Recette $recette): Response
     {
     
        if (!$recette) {
            $this->addFlash(
                'success',
                'Votre recette n/a pas été trouvé',
            );   
            return $this->redirectToRoute('app_recette');
        }
        $manager->remove($recette);
            $manager->flush();
        $this->addFlash(
            'success',
            'Votre recette  a été supprimé avec succés',
        );
        return $this->redirectToRoute('app_recette');

    }
}

templates/pages/recette/delete.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container mt-8">
        <h3>supprimer un ingrédient</h3>
                      {% for message in app.flashes ('danger') %}
     <div class='alert-danger'>
            {{message}}
      </div>
   {% endfor %}
    {% for message in app.flashes ('danger') %}
     <div class='alert-danger'>
            {{message}}
    </div>

      {% endfor %}
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_row(form.name) }}
            {{ form_errors(form.name) }}

        </div>

        <div class="form-group">
            {{ form_row(form.prix) }}
            {{ form_errors(form.prix) }}
        </div>
       
        <div class="form-group">
            {{ form_row(form.submit) }}
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}
{% block _ingredient_submit_errors %}
    {# Ce bloc gère les erreurs de soumission du formulaire #}
    {{ form_errors(form) }}

{% endblock %}

templates/pages/recette/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4">
        <h3>Ajouter une recette</h3>
         {% for message in app.flashes ('success') %}
     <div class='alert alert-success'>
            {{message}}
      </div>
   {% endfor %}
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_row(form.name) }}
            {{ form_errors(form.name) }}
            
        </div>

        <div class="form-group">
            {{ form_row(form.prix) }}
            {{ form_errors(form.prix) }}
        </div>
         <div class="form-group">
            {{ form_row(form.ingredientsL) }}
            {{ form_errors(form.ingredientsL) }}
        </div>
       
        <div class="form-group">
            {{ form_row(form.submit) }}
        </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

{% block _recette_submit_errors %}
    {# Ce bloc gère les erreurs de soumission du formulaire #}
    {{ form_errors(form) }}
{% endblock %}

templates/pages/recette/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TinRecype - Mes Recettes{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h3>Ajouter une recette</h3>
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        <div class="container mt-4">
            <h1>Mes recettes</h1>
            <a href="{{ path('recette.new') }}" class="btn btn-primary">Créer une recette</a>
            <div class="count mt-4">
                Il y a dans la liste Recettes
                {% if recettes is defined and recettes.getTotalItemCount is defined %}
                    {% if recettes.getTotalItemCount() == 0 %}
                        0
                    {% else %}
                        {{ recettes.getTotalItemCount() }}
                    {% endif %}
                {% else %}
                    0 Il n'y a pas de recettes
                {% endif %}
            </div>

            <table class="table table-active">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Date de création</th>
                        <th scope="col">Prix</th>
                        <th scope="col">Difficulty</th>
                        <th scope="col">Ingredients</th> {# Modifié "IngredientsL" à "Ingredients" #}
                        <th scope="col">Actions</th> {# Ajouté une colonne pour les actions #}
                    </tr>
                </thead>
                <tbody>
                    {% for recette in recettes %}
                        <tr class="table-active">
                            <th scope="row">{{ recette.id }} </th>
                            <td>{{ recette.name }}</td>
                            <td>{{ recette.createdAt|date('d-m-Y') }}</td>
                            <td>
                                {% if recette.prix is null %}
                                    Non renseigné
                                {% else %}
                                    {{ recette.prix }} 
                                {% endif %}
                            </td>
                            <td>
                                {% if recette.difficulty is null %}
                                    Non renseigné
                                {% else %}
                                    {{ recette.difficulty }} 
                                {% endif %}
                            </td>
                           <td>
                         {% if recette.ingredientsL is null %}
                          Non renseigné
                         {% else %}
                         {% for ingredient in recette.ingredientsL %}
                            {{ ingredient.name }} {# Assurez-vous de remplacer "nom" par le nom de la propriété de l'ingrédient que vous souhaitez afficher #}
      
                         {% endfor %}
                 {% endif %}
                        </td>
                            <td class="table mt-4">
                                <a href="{{ path('recette.edit', { id: recette.id }) }}" class="btn btn-primary ">Modifier</a>
                                <a href="{{ path('recette.delete', { id: recette.id }) }}" class="btn btn-danger " onclick="confirmModification(event)">Supprimer</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="navigation d-flex justify-content-center">
                {{ knp_pagination_render(recettes) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/recette/new.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <div class="container mt-4">
        <h3>Ajouter une recette</h3>
        
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        
        {% for message in app.flashes('danger') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}

        {{ form_start(form) }}

        <div class="form-group">
            {{ form_row(form.name) }}
            {{ form_errors(form.name) }}
        </div>

        <div class="form-group">
            {{ form_row(form.prix) }}
            {{ form_errors(form.prix) }}
        </div>

         <div class="form-group">
            {{ form_row(form.difficulty) }}
            {{ form_errors(form.difficulty) }}
        </div>
        <div class="form-group">
            {{ form_row(form.description) }}
            {{ form_errors(form.description) }}
        </div>
        <div class="form-group">
            {{ form_row(form.isFavorite) }}
            {{ form_errors(form.isFavorite) }}
        </div>
        <div class="form-group">
            {{ form_row(form.ingredientsL) }}
            {{ form_errors(form.ingredientsL) }}
        </div>

        {{ form_end(form) }}
    </div>
{% endblock %}